config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'todos', to: 'todos#index'

  get 'todos/new'
  post 'todos', to: 'todos#create'
  get 'todos/:id', to: 'todos#show', as: 'todo'
  get 'todos/:id/edit', to: 'todos#edit', as: 'edit'
  patch 'todos/:id', to: 'todos#update'
  delete 'todos/:id', to: 'todos#destroy', as: 'delete'
  get 'todos/:id/complete', to: 'todos#complete', as: 'complete'
  get 'listar', to: 'todos#list', as: 'list'


  root 'todos#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
	validates :description, presence: true 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

	def index
		@todos = Todo.all
	end

	def new
		@todo = Todo.new
	end

	def create
		todo = Todo.new(todo_params)
		todo[:completed] = false
		if todo.save
			redirect_to todo, notice: 'Se creo tarea con exito'
		else
			redirect_to todos_new_path, notice: 'No se pudo crear tarea :('
		end
	end

	def show
		@todo = Todo.find(params[:id])
	end

	def edit
		@todo = Todo.find(params[:id])
	end

	def update
		@todo = Todo.find(params[:id])
		if @todo.update(todo_params)
			redirect_to @todo, notice: 'La tarea se ha actualizado con exito'
		else
			redirect_to edit_path(@todo.id), notice: 'No se ha podido actualizar la tarea'
		end
	end

	def destroy
		@todo = Todo.find(params[:id])
		@todo.destroy
		redirect_to @todo, notice: 'El registro se ha eliminado con exito'
	end

	def complete
		@todo = Todo.find(params[:id])
		@todo[:completed] = true
		@todo.save
		redirect_to @todo, notice: 'La tarea se ha completado con exito'
	end

	def list
		@todos = Todo.all
	end


	private

	def todo_params
		params.require(:todo).permit(:description,:completed)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  		<a class="navbar-brand" href="#">Menu</a>
  		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
  			<span class="navbar-toggler-icon"></span>
  		</button>
  		<div class="collapse navbar-collapse" id="navbarNavAltMarkup">
  			<div class="navbar-nav">
  				<a class="nav-item nav-link" href="<%= todos_path %>">Index <span class="sr-only">(current)</span></a>
  				<a class="nav-item nav-link" href="<%= list_path %>">Listado Tareas</a>
  				<a class="nav-item nav-link" href="<%= todos_new_path %>">Nueva Tarea</a>
  			</div>
  		</div>
  	</nav>

    <%= yield %>
  </body>
</html>

app/views/todos/edit.html.erb
<h1>Editar Tarea</h1>

<%= form_with(model: @todo, local: true) do |form| %>
	<%= form.label :description, 'Descripcion' %>
	<%= form.text_field :description %><br><br>
	<%= form.label :completed, 'Completado' %>
	<%= form.check_box :completed %><br><br>
	<%= form.submit 'Editar' %>
<% end %><br><br>

<%= link_to 'Volver al index', todos_path %>

app/views/todos/index.html.erb
<h1>Index de Tareas</h1>
<%= notice %> <br>
<div class="">
	

	<table class="col-md-6">
		
		<% @todos.each do |todo| %>
		<tr class="card float-left">
			<td class="card-body">Descripcion: <%= todo.description  %></td>
			<td class="card-body">Completado: <%= todo.completed %></td>
			<td class="card-body"><button type=""><%= link_to 'Completado', complete_path(todo)%></button></td>
			<td class="card-body"><button type=""><%= link_to 'Show', todo_path(todo) %></button></td>
			<td class="card-body"><button type=""><%= link_to 'Edit', edit_path(todo) %></button></td>
			<td class="card-body"><button type=""><%= link_to 'Destroy', delete_path(todo), method: :delete %></button></td>
		</tr>
	<% end %> 
	</table>

</div>

app/views/todos/list.html.erb
<h2>Listado tareas</h2>

<div class="col-md-12 ">
	<div class="col-md-6 float-left">
		<h4>Completados</h4>
		<table>
			<tr>
				<th>Descripcion</th>
				<th>Completado</th>
			</tr>
				<% @todos.each do |todo| %>
				<tr>
					<% if todo.completed == true %>
					<td><%= todo.description  %></td>
					<td><%= todo.completed %></td>
					<%end %>
				</tr>
				<% end %> 
		</table>
	</div>

	<div class="col-md-6 float-left">
		<h4>No Completados</h4>
		<table>
			<tr>
				<th>Descripcion</th>
				<th>Completado</th>
			</tr>
				<% @todos.each do |todo| %>
				<tr>
					<% if todo.completed == false %>
					<td><%= todo.description  %></td>
					<td><%= todo.completed %></td>
					<%end %>
				</tr>
				<% end %> 
		</table>
	</div>

</div>

<%= link_to 'Volver al index', todos_path %>

app/views/todos/new.html.erb
<h1>Crear Nueva Tarea</h1>

<%= form_with(model: @todo, local: true) do |form| %>
	<%= form.label :description, 'Descripcion' %>
	<%= form.text_field :description %><br><br>
	<%= form.submit 'Crear' %>
<% end %><br><br>

<%= link_to 'Volver al index', todos_path %>

app/views/todos/show.html.erb
<h3>Detalle de la Tarea</h3>
<h4><%= notice %></h4>
<p>
	<strong>Descripcion: </strong><%= @todo.description %><br>
	<strong>Completado: </strong><%= @todo.completed %>
</p>

<%= link_to 'Volver al index', todos_path %>